id: P008072
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1CZ911
  title: བློ་རྟགས་ཀྱི་མཐའ་དཔྱོད
  author: ''
  volumes:
    c86291cf2077497fbcb664822a585d07:
      image_group_id: I1CZ970
      title: Volume 1 of blo rtags kyi mtha' dpyod
      volume_number: 1
      total_pages: 88
      base_file: v001.txt
