id: P008072
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ911
  title: བློ་རྟགས་ཀྱི་མཐའ་དཔྱོད
  author: ''
  volumes:
    8f5a7cb4fdbc4bdda500d119ae5725cf:
      image_group_id: I1CZ970
      title: ''
      volume_number: 1
      total_pages: 88
ebook_metadata:
  title: བློ་རྟགས་ཀྱི་མཐའ་དཔྱོད
  author: ''
  sku: P008072
  cover: cover.jpg
  layers:
  - pagination
